version: "3"

services:
  auth:
    container_name: auth
    build:
      context: auth
      dockerfile: dev.Dockerfile
    volumes:
      - ./auth:/src
    ports:
      - "5100:5100"
    env_file:
      - env/auth.env
    networks:
      - mynetwork

  auth-sidecar:
    container_name: "auth-sidecar"
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "auth",
        "--app-port",
        "5100",
        "--dapr-http-port",
        "3510",
        "--dapr-grpc-port",
        "35100",
        "--placement-host-address",
        "placement:50006",
        "--log-level",
        "debug",
        "--resources-path",
        "/dapr/components",
        "--config",
        "/dapr/config/config.yaml",
        "--metrics-port",
        "9580",
      ]
    volumes:
      - ./dapr/:/dapr/
    depends_on:
      - auth
      - placement
    network_mode: service:auth

  communication:
    container_name: communication
    build:
      context: communication
      dockerfile: dev.Dockerfile
    volumes:
      - ./communication:/src
    env_file:
      - env/communication.env
    ports:
      - "5101:5101"
    networks:
      - mynetwork

  communication-sidecar:
    container_name: "communication-sidecar"
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "communication",
        "--app-port",
        "5101",
        "--dapr-http-port",
        "3511",
        "--dapr-grpc-port",
        "35101",
        "--placement-host-address",
        "placement:50006",
        "--log-level",
        "debug",
        "--resources-path",
        "/dapr/components",
        "--config",
        "/dapr/config/config.yaml",
        "--metrics-port",
        "9581",
      ]
    volumes:
      - ./dapr/:/dapr/
    depends_on:
      - communication
      - placement
    network_mode: service:communication

  redis:
    container_name: "dapr-redis"
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - mynetwork

  placement:
    container_name: "dapr-placement"
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006", "--metrics-port", "9090"]
    ports:
      - "50006:50006"
      - "9090:9090"
    depends_on:
      - redis
    networks:
      - mynetwork

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - mynetwork
    volumes:
      - "minio_data:/data"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=iamnilesh
      - MINIO_ROOT_PASSWORD=iamnilesh123
      - MINIO_DEFAULT_BUCKETS=bucket

networks:
  mynetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
