version: "3"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=iamnilesh
      - MINIO_ROOT_PASSWORD=iamnilesh123
      - MINIO_DEFAULT_BUCKETS=bucket

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
