apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: communication
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: dapr-redis:6379
    - name: redisPassword
      value:
    - name: poolSize
      value: "8"
